name: NPM Publish

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}

      - name: Install dependencies
        run: npm ci

      - name: Build library
        run: npm run build

      - name: Publish to npm
        run: npm publish --access public
        working-directory: ./dist